// radiant-types.ts (Auto-generated)
// Do not edit this file directly.

// 1. The Core Models
export interface Users {
  id: string;
  name: string;
  role: "admin" | "user";
}

export interface Todos {
  id: string;
  title: string;
  completed: boolean;
  author: string;
}

// 2. The Create / Update Inputs
export interface UsersCreate {
  name: string;
  role?: "admin" | "user";
}

export type UsersUpdate = Partial<UsersCreate>;

export interface TodosCreate {
  title: string;
  completed?: boolean;
  author: string;
}

export type TodosUpdate = Partial<TodosCreate>;

// 3. Query Builder Types
export interface UsersWhereClause {
  name?: { eq?: string; neq?: string; like?: string; in?: string[]; nin?: string[]; exists?: boolean };
  role?: { eq?: string; neq?: string; like?: string; in?: string[]; nin?: string[]; exists?: boolean };
  and?: UsersWhereClause[];
  or?: UsersWhereClause[];
}

export interface TodosWhereClause {
  title?: { eq?: string; neq?: string; like?: string; in?: string[]; nin?: string[]; exists?: boolean };
  completed?: { eq?: boolean; neq?: boolean; in?: Array<boolean>; nin?: Array<boolean>; exists?: boolean };
  author?: { eq?: string; neq?: string; in?: string[]; nin?: string[]; exists?: boolean };
  and?: TodosWhereClause[];
  or?: TodosWhereClause[];
}

// 4. Global Framework Registry
export type Collections = {
  users: Users;
  todos: Todos;
};
