FROM oven/bun:1

WORKDIR /app
# We will mount the monorepo root to /app, so no need to copy files during build
# Just install curl for healthchecks if needed
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

CMD ["bun", "run", "dev"]
