// radiant-types.ts (Auto-generated)
// Do not edit this file directly.

// 1. The Core Models
export interface Projects {
  id: string;
  projectId: string;
  apiKey: string;
  targetDir: string;
  status: "ready" | "building" | "failed";
}

// 1b. The Populated Models
export interface ProjectsPopulated {
  id: string;
  projectId: string;
  apiKey: string;
  targetDir: string;
  status: "ready" | "building" | "failed";
}

// 2. The Create / Update Inputs
export interface ProjectsCreate {
  projectId: string;
  apiKey: string;
  targetDir: string;
  status?: "ready" | "building" | "failed";
}

export type ProjectsUpdate = Partial<ProjectsCreate>;

// 3. Query Builder Types
export interface ProjectsWhereClause {
  projectId?: { eq?: string; neq?: string; like?: string; in?: string[]; nin?: string[]; exists?: boolean };
  apiKey?: { eq?: string; neq?: string; like?: string; in?: string[]; nin?: string[]; exists?: boolean };
  targetDir?: { eq?: string; neq?: string; like?: string; in?: string[]; nin?: string[]; exists?: boolean };
  status?: { eq?: string; neq?: string; like?: string; in?: string[]; nin?: string[]; exists?: boolean };
  and?: ProjectsWhereClause[];
  or?: ProjectsWhereClause[];
}

// 4. Global Framework Registry
export type Collections = {
  projects: Projects;
  __populated: {
  projects: ProjectsPopulated;
  }
};
