// runtime.ts (Auto-generated)
// Do not edit this file directly.

import { RadiantRuntime, type RadiantConfig } from '@codesordinatestudio/radiant-bun';
import type { Collections } from '../radiant-types';

// 1. Internal AST
const internalSchema = {
  "collections": [
    {
      "slug": "projects",
      "fields": [
        {
          "name": "projectId",
          "type": "text",
          "unique": true
        },
        {
          "name": "apiKey",
          "type": "text"
        },
        {
          "name": "targetDir",
          "type": "text"
        },
        {
          "name": "status",
          "type": "enum",
          "values": [
            "ready",
            "building",
            "failed"
          ],
          "default": "ready"
        }
      ]
    },
    {
      "slug": "apiKeys",
      "fields": [
        {
          "name": "key",
          "type": "text",
          "unique": true
        },
        {
          "name": "ownerName",
          "type": "text"
        },
        {
          "name": "companyName",
          "type": "text"
        },
        {
          "name": "expiresAt",
          "type": "date"
        }
      ]
    }
  ],
  "globals": [],
  "apiPrefix": "/api"
} as const;

// 2. Radiant SDK Factory
export function createRadiant(config: RadiantConfig) {
  return new RadiantRuntime<Collections>(internalSchema as any, config);
}
