export function generateTypeScript(schema: any): string {
  let output = `// index.ts (Auto-generated)
// Do not edit this file directly.

import { RadiantRuntime, type RadiantConfig } from '@codesordinatestudio/radiant-bun';

`;

  const models: string[] = [];
  const creates: string[] = [];
  const wheres: string[] = [];
  const registry: string[] = [];

  for (const col of schema.collections || []) {
    const className = col.slug.charAt(0).toUpperCase() + col.slug.slice(1);
    
    // 1. Core Model
    let modelFields = `  id: string;\n`;
    let createFields = ``;
    let whereFields = ``;

    for (const field of col.fields || []) {
      const tsType = mapToTsType(field);
      const isOptionalInModel = field.optional ? '?' : '';
      
      // Omit password from public model
      if (field.type !== 'password') {
        modelFields += `  ${field.name}${isOptionalInModel}: ${tsType};\n`;
      }

      // Create input (password is kept here, optionally if it has a default)
      const isOptionalInCreate = (field.optional || field.default !== undefined || field.name === 'id') ? '?' : '';
      createFields += `  ${field.name}${isOptionalInCreate}: ${tsType};\n`;

      // Where clause
      if (field.type === 'text' || field.type === 'string' || field.type === 'textarea' || field.type === 'email' || field.type === 'password' || field.type === 'select' || field.type === 'enum') {
        whereFields += `  ${field.name}?: { eq?: string; neq?: string; like?: string; in?: string[]; nin?: string[]; exists?: boolean };\n`;
      } else if (field.name === 'id' || field.type === 'relationship' || field.type === 'link') {
        whereFields += `  ${field.name}?: { eq?: string; neq?: string; in?: string[]; nin?: string[]; exists?: boolean };\n`;
      } else {
        whereFields += `  ${field.name}?: { eq?: ${tsType}; neq?: ${tsType}; in?: Array<${tsType}>; nin?: Array<${tsType}>; exists?: boolean };\n`;
      }
    }

    whereFields += `  and?: ${className}WhereClause[];\n`;
    whereFields += `  or?: ${className}WhereClause[];\n`;

    models.push(`export interface ${className} {\n${modelFields}}\n`);
    creates.push(`export interface ${className}Create {\n${createFields}}\n`);
    creates.push(`export type ${className}Update = Partial<${className}Create>;\n`);
    wheres.push(`export interface ${className}WhereClause {\n${whereFields}}\n`);
    
    registry.push(`  ${col.slug}: ${className};`);
  }

  output += `// 1. The Core Models\n${models.join('\n')}\n`;
  output += `// 2. The Create / Update Inputs\n${creates.join('\n')}\n`;
  output += `// 3. Query Builder Types\n${wheres.join('\n')}\n`;
  output += `// 4. Global Framework Registry\nexport type Collections = {\n${registry.join('\n')}\n};\n\n`;

  // Strip token metadata before baking
  const cleanSchema = JSON.stringify(schema, (key, value) => {
    if (key === 'targetToken' || key === 'token' || key === 'uri' || key === 'nameToken' || key === 'typeToken') {
      return undefined;
    }
    return value;
  }, 2);

  output += `// 5. Internal AST\nconst internalSchema = ${cleanSchema} as const;\n\n`;

  output += `// 6. Radiant SDK Factory\nexport function createRadiant(config: RadiantConfig) {\n`;
  output += `  return new RadiantRuntime<Collections>(internalSchema as any, config);\n`;
  output += `}\n`;

  return output;
}

function mapToTsType(field: any): string {
  let baseType = 'any';
  
  if (field.type === 'object' && field.fields) {
    const props = field.fields.map((f: any) => `${f.name}: ${mapToTsType(f)};`).join(' ');
    baseType = `{ ${props} }`;
  } else if (field.type === 'text' || field.type === 'string' || field.type === 'textarea' || field.type === 'email' || field.type === 'password' || field.type === 'relationship' || field.type === 'link' || field.type === 'date') {
    baseType = 'string';
  } else if (field.type === 'select' || field.type === 'enum') {
    const opts = field.options || field.values;
    if (opts && Array.isArray(opts)) {
      baseType = opts.map((v: any) => `"${v}"`).join(' | ');
    } else {
      baseType = 'string';
    }
  } else if (field.type === 'boolean') {
    baseType = 'boolean';
  } else if (field.type === 'number' || field.type === 'integer') {
    baseType = 'number';
  } else if (field.type === 'multiselect') {
    baseType = 'string[]';
  } else if (field.type === 'array' || field.type === 'json' || field.type === 'richtext' || field.type === 'upload') {
    baseType = 'any';
  }

  if (field.isArray) {
    return `${baseType}[]`;
  }
  return baseType;
}
