export function generateTypeScript(schema: any): string {
  let output = `// radiant-types.ts (Auto-generated)\n// Do not edit this file directly.\n\n`;

  const models: string[] = [];
  const creates: string[] = [];
  const wheres: string[] = [];
  const registry: string[] = [];

  for (const col of schema.collections || []) {
    const className = col.slug.charAt(0).toUpperCase() + col.slug.slice(1);
    
    // 1. Core Model
    let modelFields = `  id: string;\n`;
    let createFields = ``;
    let whereFields = ``;

    for (const field of col.fields || []) {
      const tsType = mapToTsType(field);
      const isOptionalInModel = field.optional ? '?' : '';
      
      // Omit password from public model
      if (field.type !== 'password') {
        modelFields += `  ${field.name}${isOptionalInModel}: ${tsType};\n`;
      }

      // Create input (password is kept here, optionally if it has a default)
      const isOptionalInCreate = (field.optional || field.default !== undefined || field.name === 'id') ? '?' : '';
      createFields += `  ${field.name}${isOptionalInCreate}: ${tsType};\n`;

      // Where clause
      if (field.type === 'string' || field.type === 'email' || field.type === 'text') {
        whereFields += `  ${field.name}?: { eq?: string; neq?: string; like?: string; in?: string[]; nin?: string[]; exists?: boolean };\n`;
      } else if (field.name === 'id' || field.type === 'link') {
        whereFields += `  ${field.name}?: { eq?: string; neq?: string; in?: string[]; nin?: string[]; exists?: boolean };\n`;
      } else {
        whereFields += `  ${field.name}?: { eq?: ${tsType}; neq?: ${tsType}; in?: Array<${tsType}>; nin?: Array<${tsType}>; exists?: boolean };\n`;
      }
    }

    whereFields += `  and?: ${className}WhereClause[];\n`;
    whereFields += `  or?: ${className}WhereClause[];\n`;

    models.push(`export interface ${className} {\n${modelFields}}\n`);
    creates.push(`export interface ${className}Create {\n${createFields}}\n`);
    creates.push(`export type ${className}Update = Partial<${className}Create>;\n`);
    wheres.push(`export interface ${className}WhereClause {\n${whereFields}}\n`);
    
    registry.push(`  ${col.slug}: ${className};`);
  }

  output += `// 1. The Core Models\n${models.join('\n')}\n`;
  output += `// 2. The Create / Update Inputs\n${creates.join('\n')}\n`;
  output += `// 3. Query Builder Types\n${wheres.join('\n')}\n`;
  output += `// 4. Global Framework Registry\nexport type Collections = {\n${registry.join('\n')}\n};\n`;

  return output;
}

function mapToTsType(field: any): string {
  let baseType = 'any';
  
  if (field.type === 'string' || field.type === 'text' || field.type === 'email' || field.type === 'password') {
    baseType = 'string';
  } else if (field.type === 'boolean') {
    baseType = 'boolean';
  } else if (field.type === 'number') {
    baseType = 'number';
  } else if (field.type === 'link') {
    baseType = 'string'; // Usually links resolve to IDs internally when creating
  } else if (field.type === 'enum') {
    baseType = field.values.map((v: string) => `"${v}"`).join(' | ');
  } else if (field.type === 'object') {
    // Generate inline type
    let objType = '{ ';
    if (field.fields) {
      for (const f of field.fields) {
        objType += `${f.name}: ${mapToTsType(f)}; `;
      }
    }
    objType += '}';
    baseType = objType;
  }

  if (field.isArray) {
    return `${baseType}[]`;
  }
  return baseType;
}
