// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api": {
    params: {};
  };
  "/mcp": {
    params: {};
  };
  "/docs/:runtime/:slug?": {
    params: {
      "runtime": string;
      "slug"?: string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api" | "/mcp" | "/docs/:runtime/:slug?";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/api.tsx": {
    id: "routes/api";
    page: "/api";
  };
  "routes/mcp.tsx": {
    id: "routes/mcp";
    page: "/mcp";
  };
  "routes/doc.tsx": {
    id: "routes/doc";
    page: "/docs/:runtime/:slug?";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/api": typeof import("./app/routes/api.tsx");
  "routes/mcp": typeof import("./app/routes/mcp.tsx");
  "routes/doc": typeof import("./app/routes/doc.tsx");
};