// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/docs/example": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/docs/example";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/docs.example.tsx": {
    id: "routes/docs.example";
    page: "/docs/example";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/docs.example": typeof import("./app/routes/docs.example.tsx");
};