// index.ts (Auto-generated)
// Do not edit this file directly.

import { RadiantRuntime, type RadiantConfig } from '@codesordinatestudio/radiant-bun';

// 1. The Core Models
export interface Users {
  id: string;
  name: string;
  role: any;
}

export interface Todos {
  id: string;
  title: string;
  completed: boolean;
  author: string;
}

// 2. The Create / Update Inputs
export interface UsersCreate {
  name: string;
  role?: any;
}

export type UsersUpdate = Partial<UsersCreate>;

export interface TodosCreate {
  title: string;
  completed?: boolean;
  author: string;
}

export type TodosUpdate = Partial<TodosCreate>;

// 3. Query Builder Types
export interface UsersWhereClause {
  name?: { eq?: string; neq?: string; like?: string; in?: string[]; nin?: string[]; exists?: boolean };
  role?: { eq?: any; neq?: any; in?: Array<any>; nin?: Array<any>; exists?: boolean };
  and?: UsersWhereClause[];
  or?: UsersWhereClause[];
}

export interface TodosWhereClause {
  title?: { eq?: string; neq?: string; like?: string; in?: string[]; nin?: string[]; exists?: boolean };
  completed?: { eq?: boolean; neq?: boolean; in?: Array<boolean>; nin?: Array<boolean>; exists?: boolean };
  author?: { eq?: string; neq?: string; in?: string[]; nin?: string[]; exists?: boolean };
  and?: TodosWhereClause[];
  or?: TodosWhereClause[];
}

// 4. Global Framework Registry
export type Collections = {
  users: Users;
  todos: Todos;
};

// 5. Internal AST
const internalSchema = {
  "collections": [
    {
      "slug": "users",
      "fields": [
        {
          "name": "name",
          "type": "text"
        },
        {
          "name": "role",
          "type": "enum",
          "values": [
            "admin",
            "user"
          ],
          "default": "user"
        }
      ],
      "auth": true
    },
    {
      "slug": "todos",
      "fields": [
        {
          "name": "title",
          "type": "text"
        },
        {
          "name": "completed",
          "type": "boolean",
          "default": false
        },
        {
          "name": "author",
          "type": "relationship",
          "target": "users"
        }
      ]
    }
  ],
  "core": {
    "api": {
      "prefix": "/api",
      "maxBodyBytes": 1048576,
      "trustedProxies": [
        "127.0.0.1"
      ]
    }
  },
  "adminUI": {
    "enabled": true,
    "user": "users"
  },
  "security": {
    "auth": {
      "strategies": [
        "jwt",
        "session"
      ],
      "jwt": {
        "accessTokenExpiry": {
          "$env": "JWT_EXPIRY",
          "$default": "15m"
        },
        "refreshTokenExpiry": "7d",
        "cookies": {
          "enabled": true
        }
      },
      "passwordPolicy": {
        "minLength": 8,
        "requireUppercase": true,
        "requireNumber": true
      },
      "lockout": {
        "maxAttempts": {
          "$env": "LOGIN_ATTEMPTS",
          "$default": 5
        },
        "durationMinutes": 15
      }
    },
    "cors": {
      "origin": [
        "http://localhost:3000"
      ],
      "credentials": true
    },
    "rateLimit": {
      "write": {
        "max": 100,
        "window": "15m"
      },
      "login": {
        "max": 5,
        "window": "15m"
      }
    },
    "headers": {
      "enabled": true
    },
    "secrets": {
      "enabled": true
    },
    "audit": {
      "enabled": false
    }
  },
  "monitoring": {
    "healthCheck": {
      "enabled": true,
      "path": "/health",
      "requiresAuth": false
    },
    "requestId": {
      "enabled": true
    }
  }
} as const;

// 6. Radiant SDK Factory
export function createRadiant(config: RadiantConfig) {
  return new RadiantRuntime<Collections>(internalSchema as any, config);
}
