// radiant-types.ts (Auto-generated)
// Do not edit this file directly.

// 1. The Core Models

// 1b. The Populated Models

// 2. The Create / Update Inputs

// 3. Query Builder Types

// 4. Global Framework Registry
export type Collections = {

  __populated: {

  }
};
