// runtime.ts (Auto-generated)
// Do not edit this file directly.

import { RadiantRuntime, type RadiantConfig } from '@codesordinatestudio/radiant-bun';
import type { Collections } from '../radiant-types';

// 1. Internal AST
const internalSchema = {
  "collections": [],
  "globals": [],
  "apiPrefix": "/v4"
} as const;

// 2. Radiant SDK Factory
export function createRadiant(config: RadiantConfig) {
  return new RadiantRuntime<Collections>(internalSchema as any, config);
}
