// radiant-types.ts (Auto-generated)
// Do not edit this file directly.

// 1. The Core Models
export interface Users {
  id: string;
  name: string;
  role: "admin" | "user";
}

export interface Todos {
  id: string;
  title: string;
  completed: boolean;
  author: string;
}

// 2. The Create / Update Inputs
export interface UsersCreate {
  name: string;
  role?: "admin" | "user";
}

export type UsersUpdate = Partial<UsersCreate>;

export interface TodosCreate {
  title: string;
  completed?: boolean;
  author: string;
}

export type TodosUpdate = Partial<TodosCreate>;

// 3. Query Builder Types
export interface UsersWhereInput {
  name?: { equals?: string; contains?: string };
  role?: { equals?: "admin" | "user" };
}

export interface TodosWhereInput {
  title?: { equals?: string; contains?: string };
  completed?: { equals?: boolean };
  author?: { id?: string };
}

// 4. Global Framework Registry
export type Collections = {
  users: Users;
  todos: Todos;
};
